#pragma once

#define WRES_ICON_ICO 128
#define NOTIFICATION_STRUCTURE_UID 1343061
#define TRAY_ICON_CALLBACK_ID 0x9A10

#define PRINTFX_MENU_TRAY_RIGHTCLICK 200

#define PRINTFX_MENU_ENTRY_VERSION 201
#define PRINTFX_MENU_ENTRY_EXIT 202

#define CUSTOM_THREAD_IS_DOWN (WM_APP + 1)
